# Generated by Django 6.0.4 on 2026-06-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_analyzed_at_and_issueclaim"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recommendation",
            name="pr_created_at",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="email_verified",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="target_repo",
        ),
    ]
